### ISSUE TITLE
Thank you for your excellent work, can you upload the checkpoint?

### ISSUE THREAD

**Issue by bongbongtiao** [rruisong/CoHFF#1]
Thank you for your excellent work, can you upload the checkpoint?

**Comment by rruisong** [comment]
Thank you for the issue. We will release our models one by one via this link: https://drive.google.com/drive/folders/1VdCBJ2UVdeEysaZJkYATmgOYLv9CisMp?hl=de

**Comment by jiadong825** [comment]
Hi, any updates?
