### ISSUE TITLE
Apology for Unintentionally Moving Shared Data

### ISSUE THREAD

**Issue by SHEVIP** [rruisong/CoHFF#3]
I sincerely **apologize for accidentally moving the data** you shared to my Google Drive. In an effort to remedy this, I have created a shortcut to the file in the original folder. I deeply regret any inconvenience this may have caused.

Additionally, I noticed that downloading the file from Google Drive seems quite challenging. Could you please advise if there is an **alternative method to access the dataset**?

my gratitude for your outstanding work!
Thank you for your understanding and assistance.

**Comment by rruisong** [comment]
Hi, thanks for your comment. I’ve checked the data, and everything looks good, so no need to worry. At the moment, I’m using my personal Google Drive account to share the dataset. Unfortunately, we don’t have plans to share it on any other platform at this time. Do you have any suggestions for a better platform?

**Comment by SHEVIP** [comment]
Hi, thanks for checking the data.
Could you share a **Baidu Netdisk** link instead? It would avoid waiting for Google Drive compression and doesn't require a fast network. Thanks!
