### ISSUE TITLE
Missing Files in CoHFF Dataset

### ISSUE THREAD

**Issue by Zz-dong** [rruisong/CoHFF#4]
Thank you for your excellent work. I noticed that two files seem to be missing in the [4LidarCampos/train](https://drive.google.com/drive/folders/1mYMhO2Xh6gazsiNJ-IgZAP1OMZZm3eFv) folder, compared to the original OPV2V dataset. Specifically, the following files are not present: 

- 2021_08_16_22_26_54.zip
- 2021_09_09_13_20_58.zip

**Comment by chrisyan** [comment]
Hi [Zz-dong,
We checked the dataset again and uploaded the missing files.

**Comment by jiadong825** [comment]
That's great. Thanks.
